theme: jekyll-theme-cayman

#paginate: 10
#plugins: [jekyll-paginate]

title: Nederlands Security Meldpunt
description: Het Nederlandse meldunt voor 
#url: https://www.seccubus.com
#baseurl:
timezone: Europe/Amsterdam
future: true
encoding: utf-8

permalink: pretty
#paginate_path: "news/:num/"
#highlighter: rouge
markdown: kramdown
#redcarpet:
#    extensions:
#        - no_intra_emphasis
#        - autolink
#        - strikethrough
#        - fenced_code_blocks